# Generated by Django 2.2 on 2020-10-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_auto_20201020_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Добавить фото'),
        ),
    ]
