# Generated by Django 2.2 on 2020-10-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_auto_20201020_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_journal',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Добавить фото журнала'),
        ),
    ]
