# Generated by Django 2.2.16 on 2020-10-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0011_post_img_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file_contents',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Добавить файл содержания'),
        ),
    ]
