# Generated by Django 2.2.16 on 2020-10-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0017_auto_20201027_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='file_contents',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Добавить файл содержания'),
        ),
    ]
