# Generated by Django 2.2.16 on 2020-10-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0018_product_file_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file_contents',
            field=models.FileField(blank=True, null=True, upload_to='products/', verbose_name='Добавить файл содержания'),
        ),
    ]
