# Generated by Django 2.2.16 on 2020-10-30 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0022_auto_20201030_1123'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='product',
            index_together=None,
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
