# Generated by Django 2.2 on 2020-11-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0025_auto_20201102_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file_contents',
            field=models.FileField(blank=True, default='static/logo-naks-gray.png', null=True, upload_to='uploads/', verbose_name='Добавить файл содержания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='file_contents',
            field=models.FileField(blank=True, default='static/logo-naks-gray.png', null=True, upload_to='products/', verbose_name='Добавить файл содержания'),
        ),
    ]
