# Generated by Django 2.2 on 2020-11-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0027_auto_20201102_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='num',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Порядок вывода'),
        ),
    ]
